steps:
  - name: 'python:3.11'
    entrypoint: 'bash'
    args:
      - -lc
      - |
        python -V
        pip install -U pip
        pip install -e .[dev]
        python -m synapse.infra.doctor
        python -m pytest -q
